### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by T-baby** [Joker-Jelly/deft-request#1]
这个库支持put和delete吗？还有就是为啥代码中那么webpack相关的。。0.0

**Comment by Joker-Jelly** [comment]
Hi，回答一下，这个库并不支持put和delete；webpack相关内容是因为打包输出是直接用的webpack

**Comment by Joker-Jelly** [comment]
如果想在项目中用，建议用模块引入的方式，最后自己打包起来；页面直接引用，可以引uglifiy后的 catta-min.js
